# Generated by Django 2.0.4 on 2018-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='body',
            field=models.TextField(),
        ),
    ]
